plugins {
    id 'com.android.application'
}

android {
    namespace 'cloud.kosch.corpnet'
    compileSdk 36

    defaultConfig {
        applicationId 'cloud.kosch.corpnet'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}
